/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as PerusahaanRouteImport } from './routes/perusahaan'
import { Route as InsightIndexRouteImport } from './routes/insight/index'
import { Route as InsightSlugRouteImport } from './routes/insight/$slug'
import { Route as LayananIndexRouteImport } from './routes/layanan/index'
import { Route as LayananSlugRouteImport } from './routes/layanan/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const PerusahaanRoute = PerusahaanRouteImport.update({
  id: '/perusahaan',
  path: '/perusahaan',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightIndexRoute = InsightIndexRouteImport.update({
  id: '/insight/',
  path: '/insight/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightSlugRoute = InsightSlugRouteImport.update({
  id: '/insight/$slug',
  path: '/insight/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananIndexRoute = LayananIndexRouteImport.update({
  id: '/layanan/',
  path: '/layanan/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananSlugRoute = LayananSlugRouteImport.update({
  id: '/layanan/$slug',
  path: '/layanan/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/perusahaan': typeof PerusahaanRoute
  '/insight/$slug': typeof InsightSlugRoute
  '/layanan/$slug': typeof LayananSlugRoute
  '/insight/': typeof InsightIndexRoute
  '/layanan/': typeof LayananIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/perusahaan': typeof PerusahaanRoute
  '/insight/$slug': typeof InsightSlugRoute
  '/layanan/$slug': typeof LayananSlugRoute
  '/insight': typeof InsightIndexRoute
  '/layanan': typeof LayananIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/perusahaan': typeof PerusahaanRoute
  '/insight/$slug': typeof InsightSlugRoute
  '/layanan/$slug': typeof LayananSlugRoute
  '/insight/': typeof InsightIndexRoute
  '/layanan/': typeof LayananIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeri'
    | '/kontak'
    | '/perusahaan'
    | '/insight/$slug'
    | '/layanan/$slug'
    | '/insight/'
    | '/layanan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeri'
    | '/kontak'
    | '/perusahaan'
    | '/insight/$slug'
    | '/layanan/$slug'
    | '/insight'
    | '/layanan'
  id:
    | '__root__'
    | '/'
    | '/galeri'
    | '/kontak'
    | '/perusahaan'
    | '/insight/$slug'
    | '/layanan/$slug'
    | '/insight/'
    | '/layanan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  KontakRoute: typeof KontakRoute
  PerusahaanRoute: typeof PerusahaanRoute
  InsightSlugRoute: typeof InsightSlugRoute
  LayananSlugRoute: typeof LayananSlugRoute
  InsightIndexRoute: typeof InsightIndexRoute
  LayananIndexRoute: typeof LayananIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perusahaan': {
      id: '/perusahaan'
      path: '/perusahaan'
      fullPath: '/perusahaan'
      preLoaderRoute: typeof PerusahaanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight/': {
      id: '/insight/'
      path: '/insight'
      fullPath: '/insight/'
      preLoaderRoute: typeof InsightIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight/$slug': {
      id: '/insight/$slug'
      path: '/insight/$slug'
      fullPath: '/insight/$slug'
      preLoaderRoute: typeof InsightSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan/': {
      id: '/layanan/'
      path: '/layanan'
      fullPath: '/layanan/'
      preLoaderRoute: typeof LayananIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan/$slug': {
      id: '/layanan/$slug'
      path: '/layanan/$slug'
      fullPath: '/layanan/$slug'
      preLoaderRoute: typeof LayananSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  KontakRoute: KontakRoute,
  PerusahaanRoute: PerusahaanRoute,
  InsightSlugRoute: InsightSlugRoute,
  LayananSlugRoute: LayananSlugRoute,
  InsightIndexRoute: InsightIndexRoute,
  LayananIndexRoute: LayananIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
